### ISSUE TITLE
FreeBSD 10/11 clang compilation fail

### ISSUE THREAD

**Issue by bsdmp** [vifm/vifm#99]
latest commit is failing to compile on FreeBSD 10.1/11 (clang compiler) with the message:
```
In file included from compat/getopt.c:65:
/usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
#error "<malloc.h> has been replaced by <stdlib.h>"
 ^
compat/getopt.c:573:30: warning: implicitly declaring library function 'alloca' with type 'void *(unsigned long)'
                struct option_list *newp = alloca (sizeof (*newp));
                                           ^
compat/getopt.c:573:30: note: please include the header <stdlib.h> or explicitly provide a declaration for 'alloca'
1 warning and 1 error generated.
Makefile:1060: recipe for target 'compat/getopt.o' failed
```

Commenting line 66 of compat/getopt.c fixes the issue.

**Comment by xaizek** [comment]
Thanks, should work now.

**Comment by bsdmp** [comment]
Yes, it works, thank you for quick response.

Do you have any plans to release second beta? Or only full 0.8 release will follow?

**Comment by xaizek** [comment]
There were no major issues related to newest changes, so it'll be 0.8 release. It should be available in the next few days or so (I might wait for details on a strange Windows bug from 0.7.8, which I'm unable to reproduce, but do want to know what it's about).
